# Email spam prediction

In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("emails.csv")
df.shape

(5172, 3002)

In [6]:
df.head()

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0

In [7]:
df.drop(columns=['Email No.'], inplace=True)
df.head()

,the,to,ect,and,for,of,a,you,hou,in,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,0,0,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,1,0,0
2,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
4,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,1,0,0

In [9]:
df.isnull().any().value_counts()

False    3001
dtype: int64

In [10]:
X=df.iloc[:, :df.shape[1]-1]
y=df.iloc[:, -1]
X.shape, y.shape

((5172, 3000), (5172,))

# Splitting into train and test

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.15, random_state=8)

In [13]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC

In [16]:
models={"Logistic Regression": LogisticRegression(random_state=8, solver='lbfgs', max_iter=2000),
        "Linear SVM":LinearSVC(random_state=8, max_iter=3000),
        "Polynomical SVM":SVC(kernel="poly", degree=2, random_state=8),
        "RBF SVM":SVC(kernel="rbf", random_state=8),
        "Sigmoid SVM":SVC(kernel="sigmoid", random_state=8)}

In [19]:
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [22]:
for model_name, model in models.items():
    y_pred=model.fit(X_train, y_train).predict(X_test)
    print(f"Accuracy for {model_name} model : {accuracy_score(y_test, y_pred)}")

Accuracy for Logistic Regression model : 0.9806701030927835
Accuracy for Linear SVM model : 0.9755154639175257
Accuracy for Polynomical SVM model : 0.7615979381443299
Accuracy for RBF SVM model : 0.8182989690721649
Accuracy for Sigmoid SVM model : 0.6237113402061856